language: java

cache:
  directories:
  - $HOME/arcus
  - $HOME/.m2

before_install:
  - sudo apt-get install -qq build-essential autoconf automake libtool libcppunit-dev python-setuptools python-dev ant
  - sudo pip install markupsafe
  - bash install-arcus-memcached.sh develop

script:
  - mvn test -DUSE_ZK=false -DARCUS_HOST=127.0.0.1:11212 && mvn test -DUSE_ZK=true

notifications:
  email:
    if: fork = false OR type = pull_request
    recipients:
      - junhyun.park@jam2in.com
      - minkikim89@jam2in.com
      - alsdn653@jam2in.com
